In [1]:
import pandas as pd

In [6]:
pd.__file__

'/Users/kevin/dev/MyGit/pipeline/.venv/lib/python3.13/site-packages/pandas/__init__.py'

In [7]:
pd.__name__

'pandas'

In [8]:
pd.__main__

AttributeError: module 'pandas' has no attribute '__main__'

In [9]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
url = f'{prefix}yellow_tripdata_2021-07.csv.gz'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-07.csv.gz'

In [10]:
df = pd.read_csv(url)

/var/folders/q1/8t5kbswd1vqghxgym_79clsh0000gn/T/ipykernel_13736/4176769558.py:1: DtypeWarning: Columns (0: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [11]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-07-01 00:08:51,2021-07-01 00:13:05,1.0,0.8,1.0,N,90,68,1.0,5.0,3.0,0.5,0.0,0.0,0.3,8.8,2.5
1,1.0,2021-07-01 00:22:39,2021-07-01 00:25:58,1.0,0.9,1.0,N,113,90,2.0,5.0,3.0,0.5,0.0,0.0,0.3,8.8,2.5
2,1.0,2021-07-01 00:48:33,2021-07-01 00:54:58,1.0,2.8,1.0,N,88,232,2.0,10.0,3.0,0.5,0.0,0.0,0.3,13.8,2.5
3,1.0,2021-07-01 00:59:44,2021-07-01 01:07:09,1.0,1.4,1.0,N,79,249,1.0,7.0,3.0,0.5,1.5,0.0,0.3,12.3,2.5
4,1.0,2021-07-01 00:08:35,2021-07-01 00:16:28,0.0,2.0,1.0,N,142,238,1.0,8.5,3.0,0.5,0.0,0.0,0.3,12.3,2.5

In [12]:
len(df)

2821515

In [13]:
df['VendorID']

0          1.0
1          1.0
2          1.0
3          1.0
4          1.0
          ...
2821510    NaN
2821511    NaN
2821512    NaN
2821513    NaN
2821514    NaN
Name: VendorID, Length: 2821515, dtype: float64

In [14]:
df.dtypes

VendorID                 float64
tpep_pickup_datetime         str
tpep_dropoff_datetime        str
passenger_count          float64
trip_distance            float64
RatecodeID               float64
store_and_fwd_flag           str
PULocationID               int64
DOLocationID               int64
payment_type             float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

In [15]:
df.shape

(2821515, 18)

In [25]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    # nrows=100,
    dtype=dtype,
    parse_dates=parse_dates
)

In [20]:
df.dtypes

VendorID                          Int64
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                   Int64
trip_distance                   float64
RatecodeID                        Int64
store_and_fwd_flag               string
PULocationID                      Int64
DOLocationID                      Int64
payment_type                      Int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
dtype: object

In [21]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-07-01 00:08:51,2021-07-01 00:13:05,1,0.8,1,N,90,68,1,5.0,3.0,0.5,0.0,0.0,0.3,8.8,2.5
1,1,2021-07-01 00:22:39,2021-07-01 00:25:58,1,0.9,1,N,113,90,2,5.0,3.0,0.5,0.0,0.0,0.3,8.8,2.5
2,1,2021-07-01 00:48:33,2021-07-01 00:54:58,1,2.8,1,N,88,232,2,10.0,3.0,0.5,0.0,0.0,0.3,13.8,2.5
3,1,2021-07-01 00:59:44,2021-07-01 01:07:09,1,1.4,1,N,79,249,1,7.0,3.0,0.5,1.5,0.0,0.3,12.3,2.5
4,1,2021-07-01 00:08:35,2021-07-01 00:16:28,0,2.0,1,N,142,238,1,8.5,3.0,0.5,0.0,0.0,0.3,12.3,2.5

In [29]:
df[['tpep_pickup_datetime', 'tpep_dropoff_datetime']]

        tpep_pickup_datetime tpep_dropoff_datetime
0        2021-07-01 00:08:51   2021-07-01 00:13:05
1        2021-07-01 00:22:39   2021-07-01 00:25:58
2        2021-07-01 00:48:33   2021-07-01 00:54:58
3        2021-07-01 00:59:44   2021-07-01 01:07:09
4        2021-07-01 00:08:35   2021-07-01 00:16:28
...                      ...                   ...
2821510  2021-07-09 18:07:09   2021-07-09 18:27:04
2821511  2021-07-09 18:16:00   2021-07-09 18:57:00
2821512  2021-07-09 18:07:46   2021-07-09 19:07:06
2821513  2021-07-09 18:17:00   2021-07-09 18:42:00
2821514  2021-07-09 18:11:00   2021-07-09 18:30:00

[2821515 rows x 2 columns]

In [36]:
# !uv add sqlalchemy 
# !uv add psycopg2-binary

In [37]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [44]:
df.head(0)

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [76]:
df.head(0).to_sql(name= 'yellow_taxi_data', con=engine , if_exists='replace')

0

In [41]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [61]:
len(df)

21515

In [81]:
df_iter = pd.read_csv(
    url
    , dtype = dtype
    , parse_dates = parse_dates
    , iterator = True
    , chunksize = 100000

)

In [64]:
# !uv add tdqm

In [77]:
from tqdm.auto import tqdm

In [85]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name= 'yellow_taxi_data', con=engine , if_exists='append')

0it [00:00, ?it/s]

In [84]:
df_chunk = next(df_iter)
print(df_chunk.shape)
print(df_chunk.head())

(100000, 18)
        VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
200000         2  2021-07-03 13:19:38   2021-07-03 13:24:09                1
200001         2  2021-07-03 13:29:17   2021-07-03 13:45:27                1
200002         2  2021-07-03 13:53:42   2021-07-03 14:17:36                1
200003         2  2021-07-03 13:23:18   2021-07-03 13:29:26                1
200004         2  2021-07-03 13:33:34   2021-07-03 13:38:40                1

        trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
200000           1.26           1                  N            75
200001           4.10           1                  N            41
200002          15.21           1                  N           138
200003           1.63           1                  N           232
200004           0.69           1                  N           114

        DOLocationID  payment_type  fare_amount  extra  mta_tax  tip_amount  \
200000            74             2          6.0    0.0      0.5        0.00
200001            50             2         14.5    0.0      0.5        0.00
200002            87             1         41.0    0.0      0.5       10.42
200003            79             1          7.5    0.0      0.5        2.00
200004           249             1          5.5    0.0      0.5        1.76

        tolls_amount  improvement_surcharge  total_amount  \
200000          0.00                    0.3          6.80
200001          0.00                    0.3         17.80
200002          6.55                    0.3         62.52
200003          0.00                    0.3         12.80
200004          0.00                    0.3         10.56

        congestion_surcharge
200000                   0.0
200001                   2.5
200002                   2.5
200003                   2.5
200004                   2.5

In [ ]:
df.shape

(21515, 18)

In [ ]:
df.head()